--
-- ER/Studio Data Architect SQL Code Generation
-- Project :      IMDB_MIDTERM_DATAMODEL.DM1
--
-- Date Created : Tuesday, March 11, 2025 14:57:32
-- Target DBMS : Snowflake
--

-- 
-- TABLE: BRIDGE_TITLE_GENRE 
--

CREATE TABLE BRIDGE_TITLE_GENRE(
    TITLE_GENRE_SK    INTEGER         IDENTITY(1,1),
    TITLE_SK          INTEGER         NOT NULL,
    GENRE_SK          INTEGER         NOT NULL,
    DI_JOB_ID         VARCHAR(100),
    DI_LOAD_DT        DATE,
    CONSTRAINT PK_TITLE_GENRE_SK PRIMARY KEY (TITLE_GENRE_SK, TITLE_SK, GENRE_SK) 
)
;



-- 
-- TABLE: DIM_AKAS_DETAILS 
--

CREATE TABLE DIM_AKAS_DETAILS(
    AKAS_SK       INTEGER         IDENTITY(1,1),
    TITLE_SK      INTEGER         NOT NULL,
    REGION        VARCHAR(100),
    LANGUAGE      VARCHAR(50),
    DI_JOB_ID     VARCHAR(100),
    DI_LOAD_DT    DATE,
    CONSTRAINT PK_AKAS_SK PRIMARY KEY (AKAS_SK, TITLE_SK) 
)
;



-- 
-- TABLE: DIM_CHARACTERS 
--

CREATE TABLE DIM_CHARACTERS(
    CHARACTER_SK      INTEGER         IDENTITY(1,1),
    CHARACTER_NAME    VARCHAR(400)    NOT NULL,
    DI_JOB_ID         VARCHAR(100),
    DI_LOAD_DT        DATE,
    CONSTRAINT PK_CHARACTER_SK PRIMARY KEY (CHARACTER_SK) 
)
;



-- 
-- TABLE: DIM_GENRE 
--

CREATE TABLE DIM_GENRE(
    GENRE_SK      INTEGER         IDENTITY(1,1),
    GENRE         VARCHAR(100)    NOT NULL,
    DI_JOB_ID     VARCHAR(100),
    DI_LOAD_DT    DATE,
    CONSTRAINT PK_GENRE_SK PRIMARY KEY (GENRE_SK) 
)
;



-- 
-- TABLE: DIM_JOB 
--

CREATE TABLE DIM_JOB(
    JOB_SK        INTEGER         IDENTITY(1,1),
    JOB_NAME      VARCHAR(100)    NOT NULL,
    DI_JOB_ID     VARCHAR(100),
    DI_LOAD_DT    DATE,
    CONSTRAINT PK_JOB_SK PRIMARY KEY (JOB_SK) 
)
;



-- 
-- TABLE: DIM_PERSON 
--

CREATE TABLE DIM_PERSON(
    PERSON_SK       INTEGER         IDENTITY(1,1),
    NCONST          VARCHAR(15)     NOT NULL,
    PRIMARY_NAME    VARCHAR(100),
    DI_JOB_ID       VARCHAR(100),
    DI_LOAD_DT      DATE,
    CONSTRAINT PK_PERSON_SK PRIMARY KEY (PERSON_SK) 
)
;



-- 
-- TABLE: DIM_PROFESSION 
--

CREATE TABLE DIM_PROFESSION(
    PROFESSION_SK      INTEGER         IDENTITY(1,1),
    PROFESSION_NAME    VARCHAR(100)    NOT NULL,
    DI_JOB_ID          VARCHAR(100),
    DI_LOAD_DT         DATE,
    CONSTRAINT PK_PROFESSION_SK PRIMARY KEY (PROFESSION_SK) 
)
;



-- 
-- TABLE: DIM_TITLE 
--

CREATE TABLE DIM_TITLE(
    TITLE_SK         INTEGER         IDENTITY(1,1),
    TCONST           VARCHAR(15),
    PRIMARY_TITLE    VARCHAR(100),
    TITLE_TYPE       VARCHAR(100),
    START_YEAR       NUMBER(4, 0),
    IS_ADULT         BOOLEAN,
    DI_JOB_ID        VARCHAR(100),
    DI_LOAD_DT       DATE,
    CONSTRAINT PK_TITLE_SK PRIMARY KEY (TITLE_SK) 
)
;



-- 
-- TABLE: FCT_TITLE_DETAILS 
--

CREATE TABLE FCT_TITLE_DETAILS(
    TITLE_DETAILS_SK    INTEGER         IDENTITY(1,1),
    TITLE_SK            INTEGER         NOT NULL,
    PERSON_SK           INTEGER         NOT NULL,
    PROFESSION_SK       INTEGER         NOT NULL,
    CHARACTER_SK        INTEGER         NOT NULL,
    JOB_SK              INTEGER         NOT NULL,
    DI_JOB_ID           VARCHAR(100),
    DI_LOAD_DT          DATE,
    CONSTRAINT PK_TITLE_DETAILS_SK PRIMARY KEY (TITLE_DETAILS_SK, TITLE_SK, PERSON_SK, PROFESSION_SK, CHARACTER_SK, JOB_SK) 
)
;



-- 
-- TABLE: FCT_TITLE_METRICS 
--

CREATE TABLE FCT_TITLE_METRICS(
    TITLE_METRICS_SK     INTEGER          IDENTITY(1,1),
    TITLE_SK             INTEGER          NOT NULL,
    RUNTIME_MINUTES      NUMBER(38, 0),
    AVERAGE_RATING       NUMBER(5, 2),
    SEASON_NUMBER        NUMBER(38, 0),
    COUNT_OF_EPISODES    NUMBER(38, 0),
    DI_JOB_ID            VARCHAR(100),
    DI_LOAD_DT           DATE,
    CONSTRAINT PK_TITLE_METRICS_SK PRIMARY KEY (TITLE_METRICS_SK, TITLE_SK) 
)
;



-- 
-- TABLE: BRIDGE_TITLE_GENRE 
--

ALTER TABLE BRIDGE_TITLE_GENRE ADD CONSTRAINT RefDIM_TITLE31 
    FOREIGN KEY (TITLE_SK)
    REFERENCES DIM_TITLE(TITLE_SK)
;

ALTER TABLE BRIDGE_TITLE_GENRE ADD CONSTRAINT RefDIM_GENRE41 
    FOREIGN KEY (GENRE_SK)
    REFERENCES DIM_GENRE(GENRE_SK)
;


-- 
-- TABLE: DIM_AKAS_DETAILS 
--

ALTER TABLE DIM_AKAS_DETAILS ADD CONSTRAINT RefDIM_TITLE21 
    FOREIGN KEY (TITLE_SK)
    REFERENCES DIM_TITLE(TITLE_SK)
;


-- 
-- TABLE: FCT_TITLE_DETAILS 
--

ALTER TABLE FCT_TITLE_DETAILS ADD CONSTRAINT RefDIM_TITLE51 
    FOREIGN KEY (TITLE_SK)
    REFERENCES DIM_TITLE(TITLE_SK)
;

ALTER TABLE FCT_TITLE_DETAILS ADD CONSTRAINT RefDIM_PERSON71 
    FOREIGN KEY (PERSON_SK)
    REFERENCES DIM_PERSON(PERSON_SK)
;

ALTER TABLE FCT_TITLE_DETAILS ADD CONSTRAINT RefDIM_PROFESSION81 
    FOREIGN KEY (PROFESSION_SK)
    REFERENCES DIM_PROFESSION(PROFESSION_SK)
;

ALTER TABLE FCT_TITLE_DETAILS ADD CONSTRAINT RefDIM_CHARACTERS91 
    FOREIGN KEY (CHARACTER_SK)
    REFERENCES DIM_CHARACTERS(CHARACTER_SK)
;

ALTER TABLE FCT_TITLE_DETAILS ADD CONSTRAINT RefDIM_JOB101 
    FOREIGN KEY (JOB_SK)
    REFERENCES DIM_JOB(JOB_SK)
;


-- 
-- TABLE: FCT_TITLE_METRICS 
--

ALTER TABLE FCT_TITLE_METRICS ADD CONSTRAINT RefDIM_TITLE111 
    FOREIGN KEY (TITLE_SK)
    REFERENCES DIM_TITLE(TITLE_SK)
;


